# bag_grp_dmg_vlu_deep_dive

In [8]:
def unq_val(df, l_col):
    """
    Purpose:
      - Create dataframe to include  
        - df0: keep feature name 
        - df1: get count for unique values from the feature
        - df2: get ratio of count for unique values from the feature 
        - df3: Merge df1 and df2 
      - Concating dfy, df0, df3 with axis = 0 
    Parameter
     input 
      df : df to be analyzed 
      l_col:  list of features
     output 
      dfy : dataframe for the count of unique values and  ratio of unique values    
    """
    dfy =  pd.DataFrame() 
    l_comment=[]
    for fea in l_col:   
       
          
           df0 = pd.DataFrame([[fea,'','', ' ']],columns=['feature','value','cnt','ratio_cnt'] )
           df1 = df[fea].value_counts(dropna = False).to_frame(name = 'cnt').reset_index()
           df1.rename(columns={'index':'value'}, inplace = True)
           sd =  df[fea].value_counts(dropna = False)/len(df)
           df2 = sd.to_frame(name='ratio_cnt').reset_index()
           df2.rename(columns={'index':'value'}, inplace = True)
           df3 = df1.merge(df2, on = 'value',how = 'inner')
           dfy = pd.concat([dfy,  df0, df3], axis = 0)
    dfy['feature'] = dfy['feature'].replace(np.NaN, '')
    dfy['value'] = dfy['value'].replace(np.NaN, 'missing')

    return dfy

In [1]:
import numpy as np
import pandas as pd
pd.options.display.float_format = '{:,.4f}'.format
pd.set_option('display.max_columns', None) 
pd.set_option("display.max_rows", None)

In [3]:
path = 'C:\\users\\iny2819\\kroger\\Data\\'
path_file =  path + 'bag_grp_dmg_vlu.xlsx'
df = pd.read_excel(path_file)

In [4]:
df.shape

(95278, 88)

In [6]:
df.head()

,ITM_OC_ATB_ID,ITM_ID,VND_PRVD_EXP_DT,KRG_OWN_HAS_EXP_DT,KRG_SHD_ELG_FL,ATB_CHG_SIN_LST_MER_TX,MER_TO_MAS_VLU,KRG_OWN_SGE_TPT_ICR_CD,KRG_OWN_DLV_TPT_ICR_CD,KRG_IDC_FIRE_PVNN_SGE_FL,ITM_STD_MIN_DLV_LIF,MIN_DLV_LIF,KRG_OWN_SGE_TPT_ICR_VLU,KRG_OWN_DLV_TPT_ICR_VLU,CHG_EVT_CD,CHG_EVT_VLU,LST_UPD_TS,KRG_OWN_IS_RAW_CD,KRG_OWN_IS_RAW_VLU,KRG_OWN_IS_CHEM_CD,KRG_OWN_IS_CHEM_VLU,TTE_TYP_CD,TTE_TYP_VLU,BAG_GRP_DMG_CD,BAG_GRP_DMG_VLU,DETR_MTD_CD,DETR_MTD_VLU,RCV_HND_IST_CD,RCV_HND_IST_VLU,PIK_HND_IST_CD,PIK_HND_IST_VLU,WNE_HLD_CGY_CD,WNE_HLD_CGY_VLU,MAX_TTE_FIL,CUB_SEGR_CLS_AMBI_CD,CUB_SEGR_CLS_AMBI_VLU,CUB_SEGR_CLS_CHIL_CD,CUB_SEGR_CLS_CHIL_VLU,MAX_RCT_ALD_PN,MAX_ACPABL_RCT_LIF,MAX_USR_ADJ_ITM,ITM_VOL_CUB_INCH,PIK_ZNE_CD,PIK_ZNE_VLU,RCB_ZNE_CD,RCB_ZNE_VLU,BAG_SPA_CGY_CD,BAG_SPA_CGY_VLU,RSV_FL,DSA_REPT_SCN_FL,ESST_FL,RCB_FL,PIK_LST_FL,DFC_TO_SCN_FL,SHF_LIF_QY,PLUM_DSC_1,PLUM_DSC_2,SHF_LIF_UOM_CD,SHF_LIF_UOM_VLU,TARE_NO,TARE_UWP_NO,PLUM_SLS_TYP_CD,PLUM_SLS_TYP_VLU,COOL_CD,COOL_VLU,SCL_PLU,RPL_TYP_CD,RPL_TYP_VLU,RPL_ITM_GTIN_NO,CVF_NO,FAC_ID,FCED_TARE,BAR_SCN_MTD_CD,BAR_SCN_MTD_VLU,MIN_RCB_LIF_DAYS,MAX_RCB_LIF_DAYS,SUP_GUA_LIF_DAYS,PLUM_DSC_3,PLUM_DSC_4,PIK_CGY_CD,PIK_CGY_VLU,FFL_CET_SLL_BY,PLUM_DPT_CD,PLUM_DPT_VLU,KRG_OWN_HGT,KRG_OWN_LTH,KRG_OWN_WTH,KRG_OWN_GRS_WGT
0,468391177,718177610,NaN,Yes,Yes,NaN,NaN,FROZEN,FROZEN,No,NaN,30.0000,Frozen,Frozen,NaN,NaN,2023-06-25 10:43:58.503,N,No,N,No,STORAGE_TOTE,Storage Tote,MEDIUM_WEIGHT,Medium Weight,REMOVE_FROM_BOX,Remove from Box,NON_MULTIPACK,Non-Multipack,NON_MULTIPACK,Non Multipack,DISALLOWED,Disallowed,54.0000,NaN,NaN,NaN,NaN,3.0000,565.0000,150.0000,63.4380,FROZEN,Frozen,FROZEN,Frozen,NORMAL,Normal,Yes,No,No,Yes,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULAR,Regular,31.0000,"1,062.0000",439.0000,NaN,NaN,PREPACKED,Prepacked,Unit,NaN,NaN,7.2500,1.7500,5.0000,0.6300
1,468391298,718175339,NaN,Yes,Yes,NaN,NaN,FROZEN,FROZEN,No,NaN,30.0000,Frozen,Frozen,NaN,NaN,2023-06-25 10:43:58.490,N,No,N,No,STORAGE_TOTE,Storage Tote,MEDIUM_WEIGHT,Medium Weight,CUT_OFF_FLAPS,Cut off Flaps,NON_MULTIPACK,Non-Multipack,NON_MULTIPACK,Non Multipack,DISALLOWED,Disallowed,24.0000,NaN,NaN,NaN,NaN,3.0000,365.0000,150.0000,116.6960,FROZEN,Frozen,FROZEN,Frozen,NORMAL,Normal,Yes,No,No,Yes,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULAR,Regular,31.0000,365.0000,182.0000,NaN,NaN,PREPACKED,Prepacked,Unit,NaN,NaN,5.7500,2.7500,7.3800,1.3300
2,468392149,718180902,NaN,Yes,Yes,NaN,NaN,FROZEN,FROZEN,No,NaN,30.0000,Frozen,Frozen,NaN,NaN,2023-06-26 01:41:59.463,N,No,N,No,STORAGE_TOTE,Storage Tote,BRUISER,Bruiser,REMOVE_FROM_BOX,Remove from Box,NON_MULTIPACK,Non-Multipack,NON_MULTIPACK,Non Multipack,DISALLOWED,Disallowed,18.0000,NaN,NaN,NaN,NaN,3.0000,720.0000,150.0000,233.7710,FROZEN,Frozen,FROZEN,Frozen,NORMAL,Normal,Yes,No,No,Yes,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULAR,Regular,31.0000,"1,100.0000",670.0000,NaN,NaN,PREPACKED,Prepacked,Unit,NaN,NaN,2.7500,9.2500,9.1900,2.8000
3,468392278,718175253,NaN,Yes,Yes,NaN,NaN,FROZEN,FROZEN,No,NaN,30.0000,Frozen,Frozen,NaN,NaN,2023-06-26 01:41:59.463,N,No,N,No,STORAGE_TOTE,Storage Tote,MEDIUM_WEIGHT,Medium Weight,REMOVE_FROM_BOX,Remove from Box,NON_MULTIPACK,Non-Multipack,NON_MULTIPACK,Non Multipack,DISALLOWED,Disallowed,32.0000,NaN,NaN,NaN,NaN,3.0000,385.0000,150.0000,79.2400,FROZEN,Frozen,FROZEN,Frozen,NORMAL,Normal,Yes,No,No,Yes,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULAR,Regular,31.0000,597.0000,354.0000,NaN,NaN,PREPACKED,Prepacked,Unit,NaN,NaN,7.1500,1.5500,7.1500,0.5700
4,468392280,718176865,NaN,Yes,Yes,NaN,NaN,FROZEN,FROZEN,No,NaN,30.0000,Frozen,Frozen,NaN,NaN,2023-06-25 10:43:58.490,N,No,N,No,STORAGE_TOTE,Storage Tote,MEDIUM_WEIGHT,Medium Weight,REMOVE_FROM_BOX,Remove from Box,NON_MULTIPACK,Non-Multipack,NON_MULTIPACK,Non Multipack,DISALLOWED,Disallowed,42.0000,NaN,NaN,NaN,NaN,3.0000,549.0000,150.0000,102.7000,FROZEN,Frozen,FROZEN,Frozen,NORMAL,Normal,Yes,No,No,Yes,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULAR,Regular,31.0000,785.0000,445.0000,NaN,NaN,PREPACKED,Prepacked,Unit,NaN,NaN,6.5000,2.0000,7.9000,0.8000

In [7]:
df.describe()

,ITM_OC_ATB_ID,ITM_ID,VND_PRVD_EXP_DT,ATB_CHG_SIN_LST_MER_TX,ITM_STD_MIN_DLV_LIF,MIN_DLV_LIF,CHG_EVT_CD,CHG_EVT_VLU,MAX_TTE_FIL,MAX_RCT_ALD_PN,MAX_ACPABL_RCT_LIF,MAX_USR_ADJ_ITM,ITM_VOL_CUB_INCH,SHF_LIF_QY,TARE_NO,TARE_UWP_NO,COOL_CD,SCL_PLU,RPL_ITM_GTIN_NO,CVF_NO,MIN_RCB_LIF_DAYS,MAX_RCB_LIF_DAYS,SUP_GUA_LIF_DAYS,PLUM_DPT_CD,KRG_OWN_HGT,KRG_OWN_LTH,KRG_OWN_WTH,KRG_OWN_GRS_WGT
count,"95,278.0000","95,278.0000",0.0000,0.0000,0.0000,"71,485.0000",0.0000,0.0000,"95,260.0000","95,086.0000","69,681.0000","95,087.0000","95,205.0000","1,540.0000","1,539.0000","1,539.0000",375.0000,"1,539.0000",575.0000,575.0000,"71,446.0000","71,469.0000","71,469.0000","1,539.0000","95,195.0000","95,193.0000","95,195.0000","95,146.0000"
mean,"469,894,437.1560","719,678,296.7928",NaN,NaN,NaN,29.5100,NaN,NaN,104.6257,3.0044,542.0320,150.0150,149.5966,12.6584,0.0291,0.0025,100.4933,"237,471.0669","145,815,254,620.4922",1.2330,34.5625,926.6249,340.2474,9.4756,6.5089,3.5076,5.3755,1.7444
std,"1,450,533.6340","1,450,334.4048",NaN,NaN,NaN,28.6330,NaN,NaN,274.6529,1.0611,788.7577,5.1675,338.2161,20.1598,0.0390,0.0148,15.3025,"327,749.8540","269,874,364,796.5482",0.6285,50.3917,"1,152.7524",319.2379,7.1173,4.4435,2.9785,3.1213,10.7893
min,"468,391,147.0000","718,175,209.0000",NaN,NaN,NaN,0.0000,NaN,NaN,0.0000,1.0000,0.0000,3.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,"40,532.0000",1.0000,1.0000,1.0000,1.0000,7.0000,0.0400,0.0200,0.0500,0.0100
25%,"468,603,489.7500","718,388,496.2500",NaN,NaN,NaN,10.0000,NaN,NaN,24.0000,3.0000,182.0000,150.0000,35.6040,4.0000,0.0000,0.0000,101.0000,"4,235.5000","54,048,191.5000",1.0000,11.0000,300.0000,90.0000,7.0000,4.2500,1.8000,3.0000,0.3800
50%,"469,345,236.5000","719,128,622.5000",NaN,NaN,NaN,30.0000,NaN,NaN,48.0000,3.0000,365.0000,150.0000,68.0000,7.0000,0.0000,0.0000,103.0000,"74,612.0000","17,800,149,372.0000",1.0000,31.0000,712.0000,287.0000,9.0000,6.2500,2.7300,4.6000,0.8000
75%,"471,062,275.0000","720,847,081.7500",NaN,NaN,NaN,30.0000,NaN,NaN,98.0000,3.0000,730.0000,150.0000,144.5000,10.0000,0.0500,0.0000,106.0000,"407,930.0000","78,000,006,966.5000",1.0000,31.0000,"1,115.0000",498.0000,9.0000,8.3100,4.0500,7.0000,1.5000
max,"473,412,669.0000","723,195,820.0000",NaN,NaN,NaN,730.0000,NaN,NaN,"9,999.0000",325.0000,"9,999.0000","1,290.0000","9,999.9990",99.0000,0.2300,0.2400,106.0000,"992,980.0000","840,134,306,940.0000",6.0000,"2,636.0000","9,999.0000","9,999.0000",69.0000,925.0000,59.4000,48.0000,"1,850.0000"

In [11]:
l_col = df.columns 
l_rmv =['ITM_OC_ATB_ID', 'ITM_ID']
l_col = [x for x in  l_col if x not  in l_rmv]  

df_val_cnt = unq_val(df, l_col )

In [16]:
df_val_cnt.head()

              feature    value    cnt ratio_cnt
0     VND_PRVD_EXP_DT
0                      missing  95278    1.0000
0  KRG_OWN_HAS_EXP_DT
0                          Yes  71478    0.7502
1                           No  23787    0.2497

In [17]:
df_val_cnt.to_csv(path + "bag_grp_dmg_vlu_deep_dive.csv",index=None)

## loop each col to get value count distribution

In [18]:
l_col_itm_oc_atb = list(df_atb[df_atb['Table in PIM-Mart'] == 'ITM_OC_ATB']['Attribute Value Column Name']) 
l_rmv =['FLD_TO_OVD_VLU', 'KRG_IDCd_FIRE_PVNN_SGE_FL', 'OVD_VLU','PLUM_DPT_NO','SUP_ID_FOR_OVD_VLU']
l_col = [x for x in  l_col_itm_oc_atb if x not  in l_rmv]  
l_col = l_col + ['KRG_IDC_FIRE_PVNN_SGE_FL', 'PLUM_DPT_VLU']

NameError: name 'df_atb' is not defined